# Generated by Django 3.2.8 on 2021-10-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_book_no_of_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
